resources: []
kernelType: python_kubernetes
inputParams: []
executeParam:
  image:
    imageUrl: dataleap-cn-beijing.cr.volces.com/studio/notebook_runtime:online
  cpuCores: 1
  memoryMb: 4096
outputParams: []
configurationTag: InnerBase
computeResourceParam:
  queue: ''
  execGroupId: 0
  computingGroupId: 1062
