apiVersion: newide.studio.dataleap.volc/v1
kind: Pipeline
metadata:
  name: zyj
spec:
  activities:
    - name: zyj
      type: execute_notebook
      description: A new Notebook job
      source: WORKSPACE
      path: /Workspace/User/leaptest1/newde_workspace/zyj.ipynb
      kernelType: emr_serverless_spark_python
      engineQueue: 公共队列-Default
      computingResourceGroupName: 公共计算资源组
      sparkConf: []
      executeParam:
        image:
          imageUrl: ''
        cpuCores: 1
        memoryMb: 4096
      parameters: []
      resources: []
      metadata:
        position:
          x: 0
          'y': 40
      position:
        x: 120
        'y': 0
      computingResourceGroupId: 1062
  runAs: ''
  trigger:
    type: SCHEDULED
    pauseStatus: UNPAUSED
    frequency: daily
    cronExpression: 11 00 * * *
    priority: d5
  displayName: zyj
  description: A Pipeline for the new Notebook job
  schedulingResourceGroupName: lyt_test
  schedulingResourceGroupId: 1106
